In [1]:
import numpy as np

In [2]:
x = np.zeros(5)

In [3]:
x


array([0., 0., 0., 0., 0.])

In [4]:
y = np.ones(5)

In [5]:
y

array([1., 1., 1., 1., 1.])

In [6]:
x = [12,45,67,89]

array([12, 45, 67, 89])

In [12]:
x =np.ones(shape=(2,3), dtype='int32')

In [11]:
x

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
x.shape

(2, 3)

In [14]:
x.dtype

dtype('int32')

In [15]:
x.reshape(3,2)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [16]:
x.T

array([[1, 1],
       [1, 1],
       [1, 1]])

In [17]:
x = np.array([2,3,4,5])

In [18]:
x

array([2, 3, 4, 5])

In [20]:
y = x.reshape((2,2))

array([[2, 3],
       [4, 5]])

In [25]:
y[0]

1.0

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.random.randint(2,10,5)       #(from , to , size of the ele)

array([9, 9, 7, 6, 4])

In [32]:
  np.linspace(1,10,num=10,endpoint=False , retstep = True) #equidistant points 

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [33]:
np.logspace(1,10,num=10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [35]:
%timeit np.sum(x)

2.5 µs ± 32.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit np.sum()

In [11]:
import numpy as np
m1 = [[1,2,3],
     [4,5,6],
     [9,8,5]]    

m2 = [[4,5,6],
     [8,9,5],
     [4,3,5]]

mul = np.dot(m1 ,m2 )
%timeit mul

20.6 ns ± 0.793 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [12]:
m = []
def Multiple(List1,List2):
    try:
        for i in List1:
            for i in List2:
                k=i*i
                m.append()  
    except :
        print("Error")
    
List1=[1,2,3,5,6,7]
List2=[2,7,6,9,2,7] 

Multiple(List1,List2)

In [17]:
x = np.array([1,2,3,4,5,5,6])

In [21]:
x.ravel()

array([1, 2, 3, 4, 5, 5, 6])

In [25]:
 dx = x.reshape((-1,1)) #it takes col of the matrix and row can b anything

In [26]:
dy = x.reshape((1,-1))     # it takes rows from 1 and col cane be anything 

In [27]:
np.matmul(dy , dx)

array([[116]])

In [51]:
t = np.random.randint(1,10,5)

In [52]:
r = np.array([[1,2,3,5,8],
             [3,4,5,6,7]])

In [53]:
t+r

array([[ 8,  8, 12, 10, 10],
       [10, 10, 14, 11,  9]])