In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score , train_test_split


In [44]:
iris = datasets.load_iris()
X = iris.data[:, :4]
Y = iris.target


(150, 4)

In [3]:
df = pd.DataFrame(X, columns = iris.feature_names[:4])

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
lReg = LogisticRegression(C= 10.0 , solver="sag", multi_class="multinomial" , max_iter =1000 , tol = 0.001)

In [6]:
df.shape

(150, 4)

In [7]:
lReg.fit(df, Y)

LogisticRegression(C=10.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='sag', tol=0.001, verbose=0,
                   warm_start=False)

In [8]:
lReg.coef_

array([[ 1.2734497 ,  2.90143231, -3.93196445, -1.89478653],
       [ 0.79413962,  0.03280525, -0.23896401, -1.98317876],
       [-2.06758931, -2.93423756,  4.17092846,  3.87796528]])

In [9]:
lReg.intercept_

array([ 0.84350423,  2.07727365, -2.92077789])

In [10]:
lReg.predict([[4.95,3.2 ,1.3 , 0.2 ]]) # it takes 2D array

array([0])

In [11]:
Y[:6]

array([0, 0, 0, 0, 0, 0])

In [12]:
lReg.score(df , Y ) 

#this boundary region classification are better always as it divides data according to the classes , AND BETTER WITH THE REGRESSION 

0.98

In [13]:
x_train ,x_test, y_train , y_test = train_test_split(X , Y , test_size= 1/3 , random_state= 10) 

In [14]:
lReg.score(x_train , y_train)

0.98

In [15]:
lReg.score(x_test , y_test)

0.98

KNEIGHBOUR CLASSIFIER

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
df = pd.read_table('C:\\Users\\Saheel Bobde\\Documents\\LCO Machine_Learning\\Day 23\\fruit.txt')

C:\Users\Saheel Bobde\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


In [18]:
df.head()


fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [19]:
df.shape

(59, 7)

In [20]:
X = df[['mass' , 'width' ,'height' , 'color_score']]
Y_name = df['fruit_name']
Y = df['fruit_label']


In [21]:
knn = KNeighborsClassifier(n_neighbors =5 , algorithm='auto')

In [39]:
knn.fit(X , Y_name)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [40]:
type(X)

pandas.core.frame.DataFrame

In [41]:
knn.predict([[182 , 7.4 , 7.1 , 0.66]])

array(['apple'], dtype=object)

c is inversely proportional to sharpness of boundary lines 

SVM 